# -*- coding: utf-8 -*-
"""Phishing_Email_Detection_Rule_Based.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r2OHGP1LiFKwLEqTzmoEJ1jTnEfQrTcR

# Phishing Email Detection (Rule-Based Approach)

This notebook analyzes a dataset of emails with the goal of identifying clear patterns that distinguish phishing attempts from legitimate messages.

The process begins with exploratory data analysis (EDA), where the dataset’s structure, feature distributions, and class balance are examined in detail. This step provides a solid understanding of the data and highlights potential challenges, such as class imbalance.

Building on these insights, the notebook develops and evaluates rule-based methods for phishing detection. These approaches emphasize interpretability and provide a practical baseline for distinguishing between malicious and non-malicious emails.

# Environment Setup
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r"/content/phishing_emails.csv", index_col=[0])

print(f"Dataset loaded successfully with {df.shape[0]} rows and {df.shape[1]} columns.")

df.head()

"""# Exploratory Data Analysis (EDA)

Before creating detection rules, it’s important to understand the dataset. This step builds context and highlights challenges that may shape later work. The analysis includes:

* Checking the dataset’s dimensions to see its scale

* Summarizing features to understand their role and relevance

* Reviewing class distribution to identify imbalances between phishing and non-phishing emails

* Verifying feature data types for compatibility with downstream methods
"""

print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

df.describe(include="all").T.head(10)

df['label'].value_counts().plot(kind='bar', color=['green', 'red'])
plt.title("Class Distribution")
plt.xlabel("Label")
plt.ylabel("Count")
plt.show()

df.dtypes

"""# Analysis of Variance (ANOVA)

To evaluate which features provide meaningful separation between phishing and legitimate emails, an Analysis of Variance (ANOVA) test is applied. This method highlights the numerical features that contribute most strongly to class differentiation.

The workflow proceeds as follows:

* Feature grouping : Separate the dataset into binary and numerical feature subsets.

* Statistical testing : Apply ANOVA (f_classif) to the numerical features to measure their ability to explain variance between the two classes.

* Feature ranking : Order the numerical features by statistical significance, using p-values as the ranking criterion.

This analysis offers an early indication of which variables are likely to carry predictive power and can inform both rule-based and model-driven approaches later in the pipeline.
"""

binary_features = [col for col in df.columns if df[col].dropna().value_counts().index.isin([0,1]).all()]
numerical_features = [col for col in df.columns if col not in binary_features + ['label']]

print("Binary features (count):", len(binary_features))
print("Binary features:", binary_features)

print("Numerical features (count):", len(numerical_features))
print("Numerical features:", numerical_features)

from sklearn.feature_selection import SelectKBest, f_classif

X = df[numerical_features].fillna(0)
y = df['label']

fs = SelectKBest(score_func=f_classif, k='all')
fs.fit(X, y)

scores = pd.DataFrame({
    'feature': numerical_features,
    'f_score': fs.scores_,
    'p_value': fs.pvalues_
}).sort_values('f_score', ascending=False)

plt.figure(figsize=(10,8))
sns.barplot(
    data=scores,
    x="f_score",
    y="feature",
    palette="viridis"
)
plt.title("ANOVA F-test Feature Ranking")
plt.xlabel("F-score")
plt.ylabel("Feature")
plt.show()

pvalues = pd.DataFrame({
    'feature': numerical_features,
    'p_value': fs.pvalues_
}).sort_values('p_value')

print("Top 5 features by ANOVA p-value:")
display(pvalues.head(5))

"""Using an ANOVA test, we ranked numerical features by statistical significance (lowest p-values) to identify the strongest predictors of phishing emails. The top five features selected form the basis of our rule-based detection system:

* num_email_addresses: Number of email addresses found in the email body.

* num_urgent_keywords: Count of urgency-related words (e.g., “urgent,” “verify,” “update”).

* num_links: Number of hyperlinks contained in the email.

* num_spelling_errors: Count of misspelled words in the email content.

* num_words: Total number of words in the email body.

These features capture structural, linguistic, and behavioral signals commonly associated with phishing attempts. By focusing on these high-impact indicators, the rule-based detection system is designed to flag suspicious messages with greater precision.

#Rule-Based Detection Framework

From the ANOVA analysis, we identified five numerical features (plus one binary feature, Redirect) that are statistically significant for distinguishing phishing from legitimate websites.

In this section, we will design simple rule-based detectors using these features. The workflow will be as follows:

* Feature exploration: Examine the distribution of each selected feature across phishing vs. legitimate classes.

* Threshold sweep: Systematically test different threshold values for each feature to evaluate separation power.

* Greedy best-threshold check: Select the threshold that maximizes classification accuracy for each feature individually.

* Accuracy evaluation: Apply the derived rules to the dataset and measure accuracy, using the balanced dataset so that 50% represents random guessing.

* Conclusion: Summarize the performance of rule-based classification and set the stage for comparing against machine learning models.

## Rule A: num_email_addresses

### Feature Exploration
"""

df.num_email_addresses.fillna("NONE").unique()

plt.figure(figsize=(8,5))
sns.histplot(data=df, x="num_email_addresses", hue="label", bins=50, kde=False, element="step")
plt.xlim(0,450)
plt.title("Distribution of num_email_addresses by Label")
plt.show()

plt.figure(figsize=(8,5))
sns.stripplot(x="label", y="num_email_addresses", data=df, jitter=True, alpha=0.3)
plt.ylim(0,450)
plt.title("num_email_addresses distribution by Label")
plt.show()

"""### Threshold Sweep

To convert this feature into a simple rule, we test different thresholds.  
For each possible value of num_email_addresses we check two possible rules:

- Classify as phishing if < v
- Classify as phishing if >= v

We record the accuracy for each threshold and direction, then plot the results.
"""

possible_values = sorted(df.num_email_addresses.dropna().unique())

accuracies_num_email_addresses = []

for v in possible_values:
    tmp_rule_less = (df.num_email_addresses < v).astype(int)
    acc_less = (tmp_rule_less == df["label"]).mean()

    tmp_rule_greater = (df.num_email_addresses >= v).astype(int)
    acc_greater = (tmp_rule_greater == df["label"]).mean()

    best_acc = max(acc_less, acc_greater)
    accuracies_num_email_addresses.append((v, best_acc))

plt.figure(figsize=(12,6))
sns.pointplot(x=[c[0] for c in accuracies_num_email_addresses],
              y=[c[1] for c in accuracies_num_email_addresses])
plt.xticks(rotation=90)
plt.title("Threshold Sweep for num_email_addresses (best of < v or >= v rule)")
plt.xlabel("Threshold (v)")
plt.ylabel("Accuracy")
plt.show()

"""### Greedy Threshold Value Check

Next, we identify the best single threshold that maximizes accuracy.  
This tells us both the value of num_email_addresses that works best and the
direction of the inequality (< or >=).
"""

possible_values = sorted(df.num_email_addresses.dropna().unique())

best_threshold = None
best_accuracy = 0
best_direction = None

for v in possible_values:
    tmp_rule_less = (df.num_email_addresses < v).astype(int)
    acc_less = (tmp_rule_less == df["label"]).mean()

    tmp_rule_greater = (df.num_email_addresses >= v).astype(int)
    acc_greater = (tmp_rule_greater == df["label"]).mean()

    if acc_less > best_accuracy:
        best_accuracy = acc_less
        best_threshold = v
        best_direction = "<"

    if acc_greater > best_accuracy:
        best_accuracy = acc_greater
        best_threshold = v
        best_direction = ">="

print(f"Best threshold value: {best_threshold}, Direction: {best_direction}, Accuracy: {best_accuracy:.4f}")

"""### Accuracy Test

Finally, we implement the chosen threshold rule in the dataset and measure its
accuracy against the ground-truth labels.
"""

df["rule_a"] = (df.num_email_addresses < 1).astype(int)

rule_a_accuracy = (df["rule_a"] == df["label"]).mean()
print(rule_a_accuracy)

"""## Rule B: num_urgent_keywords

### Feature Exploration
"""

df.num_urgent_keywords.fillna("NONE").unique()

plt.figure(figsize=(8,5))
sns.histplot(data=df, x="num_urgent_keywords", hue="label", bins=50, kde=False, element="step")
plt.xlim(0,7)
plt.title("Distribution of num_urgent_keywords by Label")
plt.show()

plt.figure(figsize=(8,5))
sns.stripplot(x="label", y="num_urgent_keywords", data=df, jitter=True, alpha=0.3)
plt.ylim(0,7)
plt.title("num_urgent_keywords distribution by Label")
plt.show()

"""### Threshold Sweep"""

possible_values = sorted(df.num_urgent_keywords.dropna().unique())

accuracies_num_urgent_keywords = []

for v in possible_values:
    tmp_rule_less = (df.num_urgent_keywords < v).astype(int)
    acc_less = (tmp_rule_less == df["label"]).mean()

    tmp_rule_greater = (df.num_urgent_keywords >= v).astype(int)
    acc_greater = (tmp_rule_greater == df["label"]).mean()

    best_acc = max(acc_less, acc_greater)
    accuracies_num_urgent_keywords.append((v, best_acc))

plt.figure(figsize=(12,6))
sns.pointplot(x=[c[0] for c in accuracies_num_urgent_keywords],
              y=[c[1] for c in accuracies_num_urgent_keywords])
plt.xticks(rotation=90)
plt.title("Threshold Sweep for num_urgent_keywords (best of < v or >= v rule)")
plt.xlabel("Threshold (v)")
plt.ylabel("Accuracy")
plt.show()

"""### Greedy Threshold Value Check"""

possible_values = sorted(df.num_urgent_keywords.dropna().unique())

best_threshold = None
best_accuracy = 0
best_direction = None

for v in possible_values:
    tmp_rule_less = (df.num_urgent_keywords < v).astype(int)
    acc_less = (tmp_rule_less == df["label"]).mean()

    tmp_rule_greater = (df.num_urgent_keywords >= v).astype(int)
    acc_greater = (tmp_rule_greater == df["label"]).mean()

    if acc_less > best_accuracy:
        best_accuracy = acc_less
        best_threshold = v
        best_direction = "<"

    if acc_greater > best_accuracy:
        best_accuracy = acc_greater
        best_threshold = v
        best_direction = ">="

print(f"Best threshold value: {best_threshold}, Direction: {best_direction}, Accuracy: {best_accuracy:.4f}")

"""### Accuracy Test"""

df["rule_b"] = (df.num_urgent_keywords >= 1).astype(int)

rule_b_accuracy = (df["rule_b"] == df["label"]).mean()
print(rule_b_accuracy)

"""## Rule C: num_links

### Feature Exploration
"""

df.num_links.fillna("NONE").unique()

plt.figure(figsize=(8,5))
sns.histplot(data=df, x="num_links", hue="label", bins=50, kde=False, element="step")
plt.xlim(0,150)
plt.title("Distribution of num_links by Label")
plt.show()

plt.figure(figsize=(8,5))
sns.stripplot(x="label", y="num_links", data=df, jitter=True, alpha=0.3)
plt.ylim(0,150)
plt.title("num_links distribution by Label")
plt.show()

"""### Threshold Sweep"""

possible_values = sorted(df.num_links.dropna().unique())

accuracies_num_links = []

for v in possible_values:
    tmp_rule_less = (df.num_links < v).astype(int)
    acc_less = (tmp_rule_less == df["label"]).mean()

    tmp_rule_greater = (df.num_links >= v).astype(int)
    acc_greater = (tmp_rule_greater == df["label"]).mean()

    best_acc = max(acc_less, acc_greater)
    accuracies_num_links.append((v, best_acc))

plt.figure(figsize=(12,6))
sns.pointplot(x=[c[0] for c in accuracies_num_links],
              y=[c[1] for c in accuracies_num_links])
plt.xticks(rotation=90)
plt.title("Threshold Sweep for num_links (best of < v or >= v rule)")
plt.xlabel("Threshold (v)")
plt.ylabel("Accuracy")
plt.show()

"""### Greedy Threshold Value Check"""

possible_values = sorted(df.num_links.dropna().unique())

best_threshold = None
best_accuracy = 0
best_direction = None

for v in possible_values:
    tmp_rule_less = (df.num_links < v).astype(int)
    acc_less = (tmp_rule_less == df["label"]).mean()

    tmp_rule_greater = (df.num_links >= v).astype(int)
    acc_greater = (tmp_rule_greater == df["label"]).mean()

    if acc_less > best_accuracy:
        best_accuracy = acc_less
        best_threshold = v
        best_direction = "<"

    if acc_greater > best_accuracy:
        best_accuracy = acc_greater
        best_threshold = v
        best_direction = ">="

print(f"Best threshold value: {best_threshold}, Direction: {best_direction}, Accuracy: {best_accuracy:.4f}")

"""### Accuracy Test"""

df["rule_c"] = (df.num_links < 1).astype(int)

rule_c_accuracy = (df["rule_c"] == df["label"]).mean()
print(rule_c_accuracy)

"""## Rule D: num_spelling_errors

### Feature Exploration
"""

df.num_spelling_errors.fillna("NONE").unique()

plt.figure(figsize=(8,5))
sns.histplot(data=df, x="num_spelling_errors", hue="label", bins=50, kde=False, element="step")
plt.xlim(0,1550)
plt.title("Distribution of num_spelling_errors by Label")
plt.show()

plt.figure(figsize=(8,5))
sns.stripplot(x="label", y="num_spelling_errors", data=df, jitter=True, alpha=0.3)
plt.ylim(0,1550)
plt.title("num_spelling_errors distribution by Label")
plt.show()

"""### Threshold Sweep"""

possible_values = sorted(df.num_spelling_errors.dropna().unique())

accuracies_num_spelling_errors = []

for v in possible_values:
    tmp_rule_less = (df.num_spelling_errors < v).astype(int)
    acc_less = (tmp_rule_less == df["label"]).mean()

    tmp_rule_greater = (df.num_spelling_errors >= v).astype(int)
    acc_greater = (tmp_rule_greater == df["label"]).mean()

    best_acc = max(acc_less, acc_greater)
    accuracies_num_spelling_errors.append((v, best_acc))

plt.figure(figsize=(12,6))
sns.pointplot(x=[c[0] for c in accuracies_num_spelling_errors],
              y=[c[1] for c in accuracies_num_spelling_errors])
plt.xticks(rotation=90)
plt.title("Threshold Sweep for num_spelling_errors (best of < v or >= v rule)")
plt.xlabel("Threshold (v)")
plt.ylabel("Accuracy")
plt.show()

"""### Greedy Threshold Value Check"""

possible_values = sorted(df.num_spelling_errors.dropna().unique())

best_threshold = None
best_accuracy = 0
best_direction = None

for v in possible_values:
    tmp_rule_less = (df.num_spelling_errors < v).astype(int)
    acc_less = (tmp_rule_less == df["label"]).mean()

    tmp_rule_greater = (df.num_spelling_errors >= v).astype(int)
    acc_greater = (tmp_rule_greater == df["label"]).mean()

    if acc_less > best_accuracy:
        best_accuracy = acc_less
        best_threshold = v
        best_direction = "<"

    if acc_greater > best_accuracy:
        best_accuracy = acc_greater
        best_threshold = v
        best_direction = ">="

print(f"Best threshold value: {best_threshold}, Direction: {best_direction}, Accuracy: {best_accuracy:.4f}")

"""### Accuracy Test"""

df["rule_d"] = (df.num_spelling_errors < 18).astype(int)

rule_d_accuracy = (df["rule_d"] == df["label"]).mean()
print(rule_d_accuracy)

"""## Rule E: num_words

### Feature Exploration
"""

df.num_words.fillna("NONE").unique()

plt.figure(figsize=(8,5))
sns.histplot(data=df, x="num_words", hue="label", bins=50, kde=False, element="step")
plt.xlim(0,2000)
plt.title("Distribution of num_words by Label")
plt.show()

plt.figure(figsize=(8,5))
sns.stripplot(x="label", y="num_words", data=df, jitter=True, alpha=0.3)
plt.ylim(0,2000)
plt.title("num_words distribution by Label")
plt.show()

"""### Threshold Sweep"""

possible_values = sorted(df.num_words.dropna().unique())

accuracies_num_words = []

for v in possible_values:
    tmp_rule_less = (df.num_words < v).astype(int)
    acc_less = (tmp_rule_less == df["label"]).mean()

    tmp_rule_greater = (df.num_words >= v).astype(int)
    acc_greater = (tmp_rule_greater == df["label"]).mean()

    best_acc = max(acc_less, acc_greater)
    accuracies_num_words.append((v, best_acc))

plt.figure(figsize=(12,6))
sns.pointplot(x=[c[0] for c in accuracies_num_words],
              y=[c[1] for c in accuracies_num_words])
plt.xticks(rotation=90)
plt.title("Threshold Sweep for num_words (best of < v or >= v rule)")
plt.xlabel("Threshold (v)")
plt.ylabel("Accuracy")
plt.show()

"""### Greedy Threshold Value Check"""

possible_values = sorted(df.num_words.dropna().unique())

best_threshold = None
best_accuracy = 0
best_direction = None

for v in possible_values:
    tmp_rule_less = (df.num_words < v).astype(int)
    acc_less = (tmp_rule_less == df["label"]).mean()

    tmp_rule_greater = (df.num_words >= v).astype(int)
    acc_greater = (tmp_rule_greater == df["label"]).mean()

    if acc_less > best_accuracy:
        best_accuracy = acc_less
        best_threshold = v
        best_direction = "<"

    if acc_greater > best_accuracy:
        best_accuracy = acc_greater
        best_threshold = v
        best_direction = ">="

print(f"Best threshold value: {best_threshold}, Direction: {best_direction}, Accuracy: {best_accuracy:.4f}")

"""### Accuracy Test"""

df["rule_e"] = (df.num_words >= 37).astype(int)

rule_e_accuracy = (df["rule_e"] == df["label"]).mean()
print(rule_e_accuracy)

"""# Rule Combination

Now that we have defined five individual rules, we combine them into ensemble
decision strategies:

1. **OR Rule** → If any of the rules (A–E) fire, classify as phishing.  
   - Very sensitive, but may produce false positives.  

2. **AND Rule** → Only classify as phishing if all five rules fire.  
   - Very strict, but may miss many phishing emails.  

3. **Majority Voting** → Classify as phishing if at least k out of 5 rules fire.  
   - Balanced compromise. We test thresholds of k = 2, 3, 4.  

We then evaluate each strategy using confusion matrices and classification reports.
"""

from sklearn.metrics import classification_report, confusion_matrix

df["rules_or"] = (
    (df["rule_a"] | df["rule_b"] | df["rule_c"] | df["rule_d"] | df["rule_e"])
).astype(int)

df["rules_and"] = (
    (df["rule_a"] & df["rule_b"] & df["rule_c"] & df["rule_d"] & df["rule_e"])
).astype(int)

for k in [2, 3, 4]:
    df[f"rules_majority_{k}"] = (
        (df["rule_a"] + df["rule_b"] + df["rule_c"] + df["rule_d"] + df["rule_e"]) >= k
    ).astype(int)

print("=== OR Rule ===")
print(confusion_matrix(df["label"], df["rules_or"]))
print(classification_report(df["label"], df["rules_or"], target_names=["Legit","Phishing"]))

print("\n=== AND Rule ===")
print(confusion_matrix(df["label"], df["rules_and"]))
print(classification_report(df["label"], df["rules_and"], target_names=["Legit","Phishing"]))

for k in [2, 3, 4]:
    print(f"\n=== Majority Rule ({k} of 5) ===")
    print(confusion_matrix(df["label"], df[f"rules_majority_{k}"]))
    print(classification_report(df["label"], df[f"rules_majority_{k}"], target_names=["Legit","Phishing"]))

"""# Results and Discussion

We evaluated the performance of combined rule strategies (OR, AND, and
majority vote). Below is a summary of the findings:

### OR Rule
- **Confusion matrix:** Predicted everything as phishing.
- **Precision (Phishing):** 0.50, **Recall (Phishing):** 1.00, **Accuracy:** 0.50  
- **Interpretation:** Extremely sensitive catches all phishing emails
  (100% recall) but mislabels all legitimate emails (0% recall for Legit).  
  Not practical for real-world use.

### AND Rule
- **Precision (Phishing):** 0.73, **Recall (Phishing):** 0.12, **Accuracy:** 0.54  
- **Interpretation:** Very strict only a small fraction of phishing emails
  are detected. High false negatives. Better precision, but fails on recall.

### Majority Rule (2 of 5)
- **Precision (Phishing):** 0.51, **Recall (Phishing):** 0.98, **Accuracy:** 0.51  
- **Interpretation:** Nearly as sensitive as OR. Very high recall but extremely
  poor performance on Legit emails (high false positives).

### Majority Rule (3 of 5)
- **Precision (Phishing):** 0.54, **Recall (Phishing):** 0.93, **Accuracy:** 0.56  
- **Interpretation:** More balanced than 2/5, but still favors recall over precision.  
  Many legitimate emails misclassified.

### Majority Rule (4 of 5)
- **Precision (Phishing):** 0.62, **Recall (Phishing):** 0.63, **Accuracy:** 0.62  
- **Interpretation:** The most balanced strategy. Roughly equal precision and recall.  
  Overall accuracy: **62%**, making it the most reasonable rule-based strategy.

## Key Takeaways
- **OR rule →** too aggressive, unusable in practice.  
- **AND rule →** too conservative, misses most phishing.  
- **Majority voting (k=4) →** provides the best trade-off, achieving 62% accuracy
  with balanced precision and recall.  

This demonstrates that simple rule-based methods can provide *interpretable but limited* detection.  
Future improvements could include:
- Combining rule-based features with a machine learning model.  
- Weighting rules differently instead of treating them equally.  
- Exploring additional features (e.g., sender domain, HTML presence).

# Portfolio Highlight

For this rule-based phishing detection system, two ensemble strategies stand out:

- **Majority Rule (3 of 5)**:  
  - High recall (0.93) → detects most phishing attempts.  
  - Useful in high-risk scenarios where catching phishing is more important than occasional false alarms.  
  - Demonstrates sensitivity to the security context.  

- **Majority Rule (4 of 5)**:  
  - Balanced precision (0.62) and recall (0.63).  
  - Provides a more cautious, real-world option when false positives must be reduced.  

For my portfolio, I emphasize **3 of 5 as the best compromise** because it
reflects a practical security mindset (prioritize catching phishing attacks)
while also presenting **4 of 5 as the balanced alternative** for contexts
where over-flagging is a concern.

# Exporting Results
"""

import sys

def is_email_phishing(features, majority_threshold=3):

    rule_a = int(features["num_email_addresses"] < 1)
    rule_b = int(features["num_urgent_keywords"] >= 1)
    rule_c = int(features["num_links"] >= 1)
    rule_d = int(features["num_spelling_errors"] < 37)
    rule_e = int(features["num_words"] < 500)

    score = rule_a + rule_b + rule_c + rule_d + rule_e
    return int(score >= majority_threshold)


if __name__ == "__main__":
    if "ipykernel_launcher" in sys.argv[0] or "colab" in sys.argv[0]:
        test_cases = [
            {"num_email_addresses": 0, "num_urgent_keywords": 3, "num_links": 5, "num_spelling_errors": 10, "num_words": 200},   # very suspicious
            {"num_email_addresses": 2, "num_urgent_keywords": 0, "num_links": 1, "num_spelling_errors": 0, "num_words": 1500},  # mixed signals
            {"num_email_addresses": 5, "num_urgent_keywords": 0, "num_links": 0, "num_spelling_errors": 2, "num_words": 800},   # likely legit
            {"num_email_addresses": 0, "num_urgent_keywords": 1, "num_links": 10, "num_spelling_errors": 100, "num_words": 300},# obvious phishing
            {"num_email_addresses": 1, "num_urgent_keywords": 0, "num_links": 2, "num_spelling_errors": 20, "num_words": 400},  # borderline
        ]

        print("=== Hypothetical Email Tests ===")
        for i, case in enumerate(test_cases, 1):
            result = is_email_phishing(case, majority_threshold=3)
            label = "PHISHING" if result == 1 else "LEGIT"
            print(f"Case {i}: {case} → {label}")

    else:
        import argparse
        parser = argparse.ArgumentParser(description="Rule-based phishing email detector")
        parser.add_argument("--num_email_addresses", type=int, required=True)
        parser.add_argument("--num_urgent_keywords", type=int, required=True)
        parser.add_argument("--num_links", type=int, required=True)
        parser.add_argument("--num_spelling_errors", type=int, required=True)
        parser.add_argument("--num_words", type=int, required=True)
        parser.add_argument("--majority", type=int, default=3,
                            help="Number of rules that must fire (default=3)")

        args = parser.parse_args()
        features = vars(args)
        majority = features.pop("majority")

        result = is_email_phishing(features, majority_threshold=majority)

        if result == 1:
            print("This email is classified as PHISHING.")
        else:
            print("This email is classified as LEGITIMATE.")

"""# Demo Results

Running the function on sample test cases:

- **Case 1:** Obvious phishing (urgent keywords, many links, short length) → PHISHING  
- **Case 2:** Mixed signals → classified based on majority threshold.  
- **Case 3:** Likely legitimate (few issues, longer message) → LEGIT  
- **Case 4:** Extreme phishing indicators (urgent + many links + many errors) → PHISHING  
- **Case 5:** Borderline case → shows how threshold choice affects classification.  


# Portfolio Takeaway

This final step demonstrates that the rules are not just theoretical
they can be implemented as a practical detector.  

While accuracy is limited (~62% at best with Majority Rule 4/5), the model is:  
- **Transparent:** every rule is explainable.  
- **Lightweight:** no training required, just thresholds.  
- **Extendable:** can be combined with machine learning in the future.

This makes it an excellent **portfolio project** showing applied EDA,
statistical feature selection, heuristic engineering, and functional prototyping.

"""