# -*- coding: utf-8 -*-
"""Variable_Smoothing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_JTUz6Bg70ZKTcsCQW3ma3OyKHqbdBex
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import plotly.express as px
import plotly.graph_objects as go
from Features_SupplyBins import *
from Analysis_SupplyBins import *

pd.set_option('display.max_columns', None)

def plot_bad_rate(data, column, target='loan_status', value_ranges=None):
    # Calculate bad rate
    bad_rate = data.groupby(column)[target].mean().reset_index()
    bad_rate.columns = [column, 'Bad_Rate']

    # Calculate count and percentage population
    counts = data[column].value_counts(dropna=False).reset_index()
    counts.columns = [column, 'Count']
    counts['% Population'] = (counts['Count'] / len(data)) * 100

    # Merge bad rate and counts
    merged = pd.merge(bad_rate, counts, on=column)

    # Sort the merged data for better visualization
    merged = merged.sort_values(by=column)

    if value_ranges is not None:
        merged['Value_Range'] = value_ranges

    # Create bar plot for percentage population
    fig = px.bar(merged, x=column, y='% Population',
                 text=merged['Count'],
                 hover_name = merged['Value_Range'],
                 title=f'Bad Rate and % Population by {column}',
                 labels={column: column, '% Population': '% Population'})

    # Update bar plot to show count on bars
    fig.update_traces(textposition='outside')

    # Add line plot for bad rate
    fig.add_trace(
        go.Scatter(x=merged[column], y=merged['Bad_Rate'],
                   mode='lines+markers',
                   name='Bad Rate',
                   yaxis='y2')
    )

    # Update layout for dual y-axes
    fig.update_layout(
        uniformtext_minsize=8,
        uniformtext_mode='hide',
        yaxis=dict(
            title='% Population',
            tickformat='.2f'
        ),
        yaxis2=dict(
            title='Bad Rate',
            overlaying='y',
            side='right',
            tickformat='.2%'
        ),
        legend=dict(
            yanchor="top",
            y=0.99,
            xanchor="left",
            x=0.01
        ),
        height=600
    )

    fig.show()
    display(merged)
    return merged

def CAT_plot_bad_rate(data, column, target='loan_status', value_ranges=None):
    # Calculate bad rate
    bad_rate = data.groupby(column)[target].mean().reset_index()
    bad_rate.columns = [column, 'Bad_Rate']

    # Calculate count and percentage population
    counts = data[column].value_counts(dropna=False).reset_index()
    counts.columns = [column, 'Count']
    counts['% Population'] = (counts['Count'] / len(data)) * 100

    # Merge bad rate and counts
    merged = pd.merge(bad_rate, counts, on=column)

    # Sort the merged data for better visualization
    merged = merged.sort_values(by=['Bad_Rate'])

    if value_ranges is not None:
        merged['Value_Range'] = value_ranges

    # Create bar plot for percentage population
    fig = px.bar(merged, x=column, y='% Population',
                 text=merged['Count'],
                 hover_name = merged['Value_Range'],
                 title=f'Bad Rate and % Population by {column}',
                 labels={column: column, '% Population': '% Population'})

    # Update bar plot to show count on bars
    fig.update_traces(textposition='outside')

    # Add line plot for bad rate
    fig.add_trace(
        go.Scatter(x=merged[column], y=merged['Bad_Rate'],
                   mode='lines+markers',
                   name='Bad Rate',
                   yaxis='y2')
    )

    # Update layout for dual y-axes
    fig.update_layout(
        uniformtext_minsize=8,
        uniformtext_mode='hide',
        yaxis=dict(
            title='% Population',
            tickformat='.2f'
        ),
        yaxis2=dict(
            title='Bad Rate',
            overlaying='y',
            side='right',
            tickformat='.2%'
        ),
        legend=dict(
            yanchor="top",
            y=0.99,
            xanchor="left",
            x=0.01
        ),
        height=600
    )

    fig.show()
    display(merged)
    return merged

data = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/loan_data.csv')



def plot_bad_rate_num_updated(data, num_column, lstbin, target='loan_status'):

    data[f'{num_column}_binned'], bins = pd.cut(data[num_column], lstbin, labels=False, retbins=True,  duplicates='drop')
    value_ranges = [f'{bins[i]:.2f} - {bins[i+1]:.2f}' for i in range(len(bins)-1)]
    merged = plot_bad_rate(data, f'{num_column}_binned', target, value_ranges=value_ranges)
    describe_table = pd.DataFrame(data[num_column].describe())
    display(describe_table)
    return merged

def CAT_plot_bad_rate_num_updated(data, num_column, lstbin, target='loan_status'):

    data[f'{num_column}_binned'] = data[num_column]
    value_ranges = [lstbin[i] for i in range(len(lstbin))]
    merged = CAT_plot_bad_rate(data, f'{num_column}_binned', target, value_ranges=value_ranges)
    describe_table = pd.DataFrame(data[num_column].describe())
    display(describe_table)
    return merged

data.isna().sum()

"""## person_income"""

var = 'person_income'

data[var].isna().sum()

_, bintest = pd.qcut(data[var], 10, labels=False, retbins=True,  duplicates='drop') # to get initial bins

init_lstbin = list(bintest)

init_lstbin

"""### Int Bins"""

lstbin = [np.float64(8000.0),
 np.float64(35118.9),
 np.float64(43081.8),
 np.float64(51221.0),
 np.float64(59456.000000000015),
 np.float64(67048.0),
 np.float64(76436.80000000002),
 np.float64(88474.9),
 np.float64(103841.00000000004),
 np.float64(133276.1),
 np.float64(7200766.0)]

len(data)

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### Modified Bin"""

len(data)

lstbin = [np.float64(8000.0),
 np.float64(35118.9),
 np.float64(43081.8),
 np.float64(59456.000000000015),
 np.float64(67048.0),
 np.float64(76436.80000000002),
 np.float64(103841.00000000004),
 np.float64(133276.1),
 np.float64(7200766.0)]

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### modified_mapping"""

iv_df.plot(x = 'woe', y = 'Bad Rate', kind = 'scatter')

iv_df['log_odds'] = np.log(iv_df['Bad Rate']/(1-iv_df['Bad Rate']))

merged

merged_final = merged.merge(iv_df, on = var + '_binned', how = 'left')

merged_final

lstbin

list(merged_final['Value_Range'])

dict(zip(merged_final['Value_Range'],merged_final['woe']))

"""## person_emp_exp"""

var = 'person_emp_exp'

data[var].isna().sum()

_, bintest = pd.qcut(data[var], 10, labels=False, retbins=True,  duplicates='drop') # to get initial bins

init_lstbin = list(bintest)

init_lstbin

"""### Int Bins"""

lstbin = [0.0, 1.0, 3.0, 4.0, 5.0, 7.0, 9.0, 13.0, 125.0]

len(data)

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### Modified Bin"""

len(data)

lstbin = [0.0, 1.0, 3.0, 4.0, 5.0, 7.0, 9.0, 13.0, 125.0]

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### modified_mapping"""

iv_df.plot(x = 'woe', y = 'Bad Rate', kind = 'scatter')

iv_df['log_odds'] = np.log(iv_df['Bad Rate']/(1-iv_df['Bad Rate']))

merged

merged_final = merged.merge(iv_df, on = var + '_binned', how = 'left')

merged_final

lstbin

list(merged_final['Value_Range'])

dict(zip(merged_final['Value_Range'],merged_final['woe']))

"""## loan_amnt"""

var = 'loan_amnt'

data[var].isna().sum()

_, bintest = pd.qcut(data[var], 10, labels=False, retbins=True,  duplicates='drop') # to get initial bins

init_lstbin = list(bintest)

init_lstbin

"""### Int Bins"""

lstbin = [500.0,
 3000.0,
 4400.0,
 5400.0,
 6600.0,
 8000.0,
 10000.0,
 12000.0,
 14520.200000000026,
 19200.0,
 35000.0]

len(data)

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### Modified Bin"""

len(data)

lstbin = [500.0,
 4400.0,
 5400.0,
 6600.0,
 12000.0,
 14520.200000000026,
 19200.0,
 35000.0]

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### modified_mapping"""

iv_df.plot(x = 'woe', y = 'Bad Rate', kind = 'scatter')

iv_df['log_odds'] = np.log(iv_df['Bad Rate']/(1-iv_df['Bad Rate']))

merged

merged_final = merged.merge(iv_df, on = var + '_binned', how = 'left')

merged_final

lstbin

list(merged_final['Value_Range'])

dict(zip(merged_final['Value_Range'],merged_final['woe']))

"""## loan_int_rate"""

var = 'loan_int_rate'

data[var].isna().sum()

_, bintest = pd.qcut(data[var], 10, labels=False, retbins=True,  duplicates='drop') # to get initial bins

init_lstbin = list(bintest)

init_lstbin

"""### Int Bins"""

lstbin = [5.42, 6.99, 7.88, 9.44, 10.58, 11.01, 11.49, 12.53, 13.49, 14.97, 20.0]

len(data)

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### Modified Bin"""

len(data)

lstbin = [5.42, 6.99, 7.88, 9.44, 10.58, 11.01, 11.49, 12.53, 13.49, 14.97, 20.0]

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### modified_mapping"""

iv_df.plot(x = 'woe', y = 'Bad Rate', kind = 'scatter')

iv_df['log_odds'] = np.log(iv_df['Bad Rate']/(1-iv_df['Bad Rate']))

merged

merged_final = merged.merge(iv_df, on = var + '_binned', how = 'left')

merged_final

lstbin

list(merged_final['Value_Range'])

dict(zip(merged_final['Value_Range'],merged_final['woe']))

"""## loan_percent_income"""

var = 'loan_percent_income'

data[var].isna().sum()

_, bintest = pd.qcut(data[var], 10, labels=False, retbins=True,  duplicates='drop') # to get initial bins

init_lstbin = list(bintest)

init_lstbin

"""### Int Bins"""

lstbin = [0.0, 0.04, 0.06, 0.08, 0.1, 0.12, 0.14, 0.17, 0.21, 0.26, 0.66]

len(data)

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### Modified Bin"""

len(data)

lstbin = [0.0, 0.04, 0.06, 0.08, 0.1, 0.12, 0.14, 0.17, 0.21, 0.26, 0.66]

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### modified_mapping"""

iv_df.plot(x = 'woe', y = 'Bad Rate', kind = 'scatter')

iv_df['log_odds'] = np.log(iv_df['Bad Rate']/(1-iv_df['Bad Rate']))

merged

merged_final = merged.merge(iv_df, on = var + '_binned', how = 'left')

merged_final

lstbin

list(merged_final['Value_Range'])

dict(zip(merged_final['Value_Range'],merged_final['woe']))

"""## cb_person_cred_hist_length"""

var = 'cb_person_cred_hist_length'

data[var].isna().sum()

_, bintest = pd.qcut(data[var], 10, labels=False, retbins=True,  duplicates='drop') # to get initial bins

init_lstbin = list(bintest)

init_lstbin

"""### Int Bins"""

lstbin = [2.0, 3.0, 4.0, 6.0, 7.0, 9.0, 11.0, 30.0]

len(data)

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### Modified Bin"""

len(data)

lstbin = [2.0, 3.0, 4.0, 6.0, 7.0, 9.0, 11.0, 30.0]

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### modified_mapping"""

iv_df.plot(x = 'woe', y = 'Bad Rate', kind = 'scatter')

iv_df['log_odds'] = np.log(iv_df['Bad Rate']/(1-iv_df['Bad Rate']))

merged

merged_final = merged.merge(iv_df, on = var + '_binned', how = 'left')

merged_final

lstbin

list(merged_final['Value_Range'])

dict(zip(merged_final['Value_Range'],merged_final['woe']))

"""## credit_score"""

var = 'credit_score'

data[var].isna().sum()

_, bintest = pd.qcut(data[var], 10, labels=False, retbins=True,  duplicates='drop') # to get initial bins

init_lstbin = list(bintest)

init_lstbin

"""### Int Bins"""

lstbin = [390.0, 563.0, 591.0, 611.0, 626.0, 640.0, 652.0, 663.0, 676.0, 692.0, 850.0]

len(data)

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### Modified Bin"""

len(data)

lstbin = [390.0, 563.0, 591.0, 611.0, 626.0, 640.0, 652.0, 663.0, 676.0, 692.0, 850.0]

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### modified_mapping"""

iv_df.plot(x = 'woe', y = 'Bad Rate', kind = 'scatter')

iv_df['log_odds'] = np.log(iv_df['Bad Rate']/(1-iv_df['Bad Rate']))

merged

merged_final = merged.merge(iv_df, on = var + '_binned', how = 'left')

merged_final

lstbin

list(merged_final['Value_Range'])

dict(zip(merged_final['Value_Range'],merged_final['woe']))

"""## credit_score"""

var = 'credit_score'

data[var].isna().sum()

_, bintest = pd.qcut(data[var], 10, labels=False, retbins=True,  duplicates='drop') # to get initial bins

init_lstbin = list(bintest)

init_lstbin

"""### Int Bins"""

lstbin = [390.0, 563.0, 591.0, 611.0, 626.0, 640.0, 652.0, 663.0, 676.0, 692.0, 850.0]

len(data)

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### Modified Bin"""

len(data)

lstbin = [390.0, 563.0, 591.0, 611.0, 626.0, 640.0, 652.0, 663.0, 676.0, 692.0, 850.0]

merged = plot_bad_rate_num_updated(data, var, lstbin)

data[var + '_binned'].nunique()

feat_cat_supbins = CategoricalFeature_SupplyBins(data, var + '_binned', 'loan_status', var)

iv = IV_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### modified_mapping"""

iv_df.plot(x = 'woe', y = 'Bad Rate', kind = 'scatter')

iv_df['log_odds'] = np.log(iv_df['Bad Rate']/(1-iv_df['Bad Rate']))

merged

merged_final = merged.merge(iv_df, on = var + '_binned', how = 'left')

merged_final

lstbin

list(merged_final['Value_Range'])

dict(zip(merged_final['Value_Range'],merged_final['woe']))

"""#person_home_ownership"""

var = 'person_home_ownership'

data[var].isna().sum()

data[var].value_counts()

data[var].unique()

"""## Int Bins"""

init_lstbin = list(data[var].unique())

init_lstbin

lstbin = ['RENT', 'OWN', 'MORTGAGE', 'OTHER']

len(data)

data[var + '_cat'] = data[var]

merged = CAT_plot_bad_rate_num_updated(data, var + '_cat', lstbin)

data[var + '_cat_binned'].nunique()

feat_cat_supbins = CategoricalFeature_NoMean_SupplyBins(data, var + '_cat_binned', 'loan_status')

iv = IV_NoMean_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""## Modified"""

data['person_home_ownership_cat'] = data['person_home_ownership_cat'].replace({'OTHER': 'RENT'})

data[var].value_counts()

lstbin = ['RENT', 'OWN', 'MORTGAGE']

dict_var = dict(data[var + '_cat'].value_counts())

lstToGroup = [k for k,v in dict_var.items() if v < 100]

len(data)

for i in lstToGroup:
    lstbin.remove(i)

len(lstbin)

lstbin

data[var + '_cat'].nunique()

merged = CAT_plot_bad_rate_num_updated(data, var + '_cat', lstbin)

data[var + '_cat_binned'].nunique()

feat_cat_supbins = CategoricalFeature_NoMean_SupplyBins(data, var + '_cat_binned', 'loan_status')

iv = IV_NoMean_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### woe_mapping"""

iv_df.plot(x = 'woe', y = 'Bad Rate', kind = 'scatter')

iv_df['log_odds'] = np.log(iv_df['Bad Rate']/(1-iv_df['Bad Rate']))

merged

merged_final = merged.merge(iv_df, on = var + '_cat_binned', how = 'left')

merged_final

lstbin

list(merged_final['Value_Range'])

dict(zip(merged_final[var + '_cat_binned'],merged_final['woe']))

"""#previous_loan_defaults_on_file"""

var = 'previous_loan_defaults_on_file'

data['previous_loan_defaults_on_file'] = data['previous_loan_defaults_on_file'].map({'Yes': 'No', 'No': 'Yes'})

data[var].isna().sum()

data[var].value_counts()

data[var].unique()

"""## Int Bins"""

init_lstbin = list(data[var].unique())

init_lstbin

lstbin = ['Yes', 'No']

len(data)

data[var + '_cat'] = data[var]

merged = CAT_plot_bad_rate_num_updated(data, var + '_cat', lstbin)

data[var + '_cat_binned'].nunique()

feat_cat_supbins = CategoricalFeature_NoMean_SupplyBins(data, var + '_cat_binned', 'loan_status')

iv = IV_NoMean_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""## Modified"""

data['person_home_ownership_cat'] = data['person_home_ownership_cat'].replace({'OTHER': 'RENT'})

data[var].value_counts()

lstbin = ['Yes', 'No']

dict_var = dict(data[var + '_cat'].value_counts())

lstToGroup = [k for k,v in dict_var.items() if v < 100]

len(data)

for i in lstToGroup:
    lstbin.remove(i)

len(lstbin)

lstbin

data[var + '_cat'].nunique()

merged = CAT_plot_bad_rate_num_updated(data, var + '_cat', lstbin)

data[var + '_cat_binned'].nunique()

feat_cat_supbins = CategoricalFeature_NoMean_SupplyBins(data, var + '_cat_binned', 'loan_status')

iv = IV_NoMean_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### woe_mapping"""

iv_df.plot(x = 'woe', y = 'Bad Rate', kind = 'scatter')

iv_df['log_odds'] = np.log(iv_df['Bad Rate']/(1-iv_df['Bad Rate']))

merged

merged_final = merged.merge(iv_df, on = var + '_cat_binned', how = 'left')

merged_final

lstbin

list(merged_final['Value_Range'])

dict(zip(merged_final[var + '_cat_binned'],merged_final['woe']))

"""#previous_loan_defaults_on_file"""

var = 'previous_loan_defaults_on_file'

data['previous_loan_defaults_on_file'] = data['previous_loan_defaults_on_file'].map({'Yes': 'No', 'No': 'Yes'})

data[var].isna().sum()

data[var].value_counts()

data[var].unique()

"""## Int Bins"""

init_lstbin = list(data[var].unique())

init_lstbin

lstbin = ['Yes', 'No']

len(data)

data[var + '_cat'] = data[var]

merged = CAT_plot_bad_rate_num_updated(data, var + '_cat', lstbin)

data[var + '_cat_binned'].nunique()

feat_cat_supbins = CategoricalFeature_NoMean_SupplyBins(data, var + '_cat_binned', 'loan_status')

iv = IV_NoMean_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""## Modified"""

data['person_home_ownership_cat'] = data['person_home_ownership_cat'].replace({'OTHER': 'RENT'})

data[var].value_counts()

lstbin = ['Yes', 'No']

dict_var = dict(data[var + '_cat'].value_counts())

lstToGroup = [k for k,v in dict_var.items() if v < 100]

len(data)

for i in lstToGroup:
    lstbin.remove(i)

len(lstbin)

lstbin

data[var + '_cat'].nunique()

merged = CAT_plot_bad_rate_num_updated(data, var + '_cat', lstbin)

data[var + '_cat_binned'].nunique()

feat_cat_supbins = CategoricalFeature_NoMean_SupplyBins(data, var + '_cat_binned', 'loan_status')

iv = IV_NoMean_SupplyBins()

iv_df, iv_value = iv.calculate_iv(feat_cat_supbins, 'loan_status')
display(iv_df)
print('Information value: ', iv_value)

"""### woe_mapping"""

iv_df.plot(x = 'woe', y = 'Bad Rate', kind = 'scatter')

iv_df['log_odds'] = np.log(iv_df['Bad Rate']/(1-iv_df['Bad Rate']))

merged

merged_final = merged.merge(iv_df, on = var + '_cat_binned', how = 'left')

merged_final

lstbin

list(merged_final['Value_Range'])

dict(zip(merged_final[var + '_cat_binned'],merged_final['woe']))