# -*- coding: utf-8 -*-
"""combine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IBqDNoIEq23TuroSUOdeCgOTF__lMAtI
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

woeiv = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/Internal_iv.csv', index_col = [0]).reset_index().drop(columns = ['index'])

woeiv.head()

spear = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/spearman.csv', index_col = [0])

spear.head()

LR = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/Internal_LR.csv', index_col=[0])

LR.head()

hoeff = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/Internal_hoeff.csv', index_col=[0])

hoeff.head()

vc = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/Internal_VC_Results.csv', index_col = [0])

vc.head()

woeiv = woeiv.rename(columns = {'features':'variable', 'p_value':'iv_p_value'})

woeiv['iv_rank'] = woeiv['iv'].rank(ascending = False, method = 'dense')

woeiv = woeiv.sort_values(by = ['iv_rank']).reset_index().drop(columns = ['index'])

spear = spear.rename(columns = {'pvalue':'spear_pvalue'})

spear['spear_rank'] = spear['spearman'].rank(ascending = False, method = 'dense')

spear = spear.sort_values(by = ['spear_rank']).reset_index().drop(columns = ['index'])

LR = LR.rename(columns = {'features':'variable', 'pvalues':'LR_pvalues'})

LR['LR_rank'] = LR['LR_pvalues'].rank(ascending = True, method = 'dense')

LR = LR.sort_values(by = ['LR_rank']).reset_index().drop(columns = ['index'])

hoeff['hoeff_rank'] = hoeff['hoeff'].rank(ascending = False, method = 'dense')

hoeff = hoeff.sort_values(by = ['hoeff_rank']).reset_index().drop(columns = ['index'])

vc = vc.rename(columns = {'Variable':'variable'})

combine = woeiv.copy()

combine = combine.merge(spear, on = 'variable', how = 'left')

combine = combine.merge(LR, on = 'variable', how = 'left')

combine = combine.merge(hoeff, on = 'variable', how = 'left')

combine = combine.merge(vc, on = 'variable', how = 'left')

rf = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/Internal_Random Forest.csv', index_col=[0])
# rf2 = pd.read_csv('./Random Forest/Random Forest_FewCategorical.csv', index_col=[0])

rf = rf.rename(columns={'Feature':'variable'})
# rf2 = rf2.rename(columns={'Feature':'variable'})

xgb = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/Internal_XGBoost.csv', index_col=[0])
# xgb2 = pd.read_csv('./XGBoost/XGBoost_FewCategorical.csv', index_col=[0])

xgb = xgb.rename(columns={'Feature':'variable'})
# xgb2 = xgb2.rename(columns={'Feature':'variable'})

combine = combine.merge(rf, on='variable',how='left')
# combine = combine.merge(rf2, on='variable',how='left')

combine=combine.merge(xgb,on='variable',how='left')
# combine=combine.merge(xgb2,on='variable',how='left')

combine.head()

combine.to_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/Internal_variable_selection_combined_results.csv')

"""## Final Feature Selection Logic

To create a parsimonious and non-redundant feature set, I combined the outputs of all selection methods using the following strategy:

Top IV per Cluster: For each cluster identified in variable clustering, I selected the feature with the highest Information Value (IV) to avoid redundant variables with similar signals.

Top 30% Composite Features: Independently, I ranked all features using a normalized composite score that averaged across:

+ IV rank

+ Spearman correlation

+ Logistic regression p-values

+ Hoeffding's D statistic

+ Random Forest importance

+ XGBoost importance

Merge & Deduplicate: I merged both sets, then removed duplicates by keeping the feature with the stronger IV in case of conflict.

This approach balances predictive power (via multiple metrics) with variable diversity (by clustering), ensuring robust, interpretable inputs for downstream modeling.

Final selected features: 6 out of 11, automatically pruned for overlap and signal strength.
"""

combined_df = combine.copy()

combined_df["xgb_rank_norm"] = -combined_df["XGB_Rank"]
combined_df["rf_rank_norm"] = -combined_df["RF_Rank"]
combined_df["hoeffding_d_norm"] = -combined_df["hoeff_rank"]
combined_df["spearman_corr_norm"] = -combined_df["spear_rank"]
combined_df["lr_pvalue_norm"] = -combined_df["LR_rank"]
combined_df["iv_norm"] = -combined_df["iv_rank"]

combined_df["composite_score"] = combined_df[
    ["xgb_rank_norm", "rf_rank_norm", "hoeffding_d_norm", "spearman_corr_norm", "lr_pvalue_norm", "iv_norm"]
].mean(axis=1)

top_iv_per_cluster = combined_df.sort_values("iv", ascending=False).drop_duplicates("Cluster")

top_30_cutoff = combined_df["composite_score"].quantile(0.7)
top_by_composite = combined_df[combined_df["composite_score"] >= top_30_cutoff]

final_features = pd.concat([top_iv_per_cluster, top_by_composite]).drop_duplicates("variable")

final_features = final_features[final_features["iv"] >= 0.02]

final_features.to_csv("final_selected_features.csv", index=False)

print(f"Selected {final_features.shape[0]} final variables")

final_features