# -*- coding: utf-8 -*-
"""LR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NA0j2bZu1ZxIWo8lfXQ8X-lm_UbjCJ4j

# Univariate Logistic Regression Feature Screening

This notebook applies **univariate logistic regression** to assess the statistical significance of each predictor against the binary target loan_status.

Univariate logistic regression is a common first step in credit scoring workflows. It evaluates each variable individually to:

- Identify statistically significant features (low p-values)
- Eliminate variables with weak or no association
- Prioritize predictors for further modeling or binning

This approach is especially useful when working with tabular, encoded credit data and aligns with standard model governance practices (e.g., rejecting variables with p > 0.05).
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

import matplotlib.pyplot as plt
import datetime

pd.set_option('display.max_columns', None)

"""## Load Prepared Development Dataset

Loading the dataset generated during the univariate feature preparation phase. This data is clean, encoded, and ready for logistic regression analysis.
"""

data = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/Internal_test_0_datasetForUnivariateVSExceptIV.csv', index_col=[0])

data

lstfeature = list(data.columns)

len(lstfeature)

lstfeature.remove('loan_status')

len(lstfeature)

features = []
pvalues = []
coeff = []

"""## Univariate Logistic Regression Loop

This loop runs a univariate logistic regression for each feature (one at a time) against the binary target loan_status, capturing their respective p-values.

This method helps:
- Identify statistically significant predictors (low p-values)
- Filter out noisy or irrelevant variables
- Support initial feature ranking before multivariate modeling
"""

for i in lstfeature:
    features.append(i)
    modeldata = data[['loan_status', i]]
    Xtrain = modeldata[[i]]
    Xtrain = sm.add_constant(Xtrain)
    ytrain = modeldata[['loan_status']]

    try:
        log_reg = sm.Logit(ytrain, Xtrain).fit()
        pvalues.append(log_reg.pvalues[i])
        coeff.append(log_reg.params[i])
    except np.linalg.LinAlgError as err:
        if 'Singular matrix' in str(err):
            pvalues.append(1.0)
            coeff.append(0.0)
            continue
        else:
            raise

dict = {'features': features, 'pvalues': pvalues}
df = pd.DataFrame(dict)

df

"""## Rank Features by Statistical Significance

Sorting variables by their p-value gives a sense of which predictors are statistically strongest. This helps shortlist variables for further modeling or transformation.

"""

df = df.sort_values(by = ['pvalues'], ascending = True).reset_index().drop(columns = ['index'])

"""## Interpretation of Results

The table ranks each feature based on its univariate logistic regression p-value against the target loan_status.

- Features like person_income, loan_int_rate, and loan_percent_income show **strong statistical significance** (p < 0.001), suggesting a meaningful relationship with default likelihood.
- Variables such as credit_score, person_education, and especially previous_loan_defaults_on_file exhibit **weak or no statistical significance**, with p-values above common rejection thresholds (e.g., 0.05).
- This step helps **filter out irrelevant predictors** and prioritizes those for further smoothing, binning, or multivariate analysis.

> Note: While statistical significance is important, it does not guarantee predictive power, further validation through model performance and multicollinearity checks is recommended.

"""

df

df.to_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/Internal_LR.csv')