# -*- coding: utf-8 -*-
"""Spearman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q07Jt6Jbo3ocKghXIuWtz6R9dkjXWj19

# Spearman Correlation Analysis

This notebook evaluates monotonic relationships between each feature and the binary target loan_status using **Spearman's rank correlation**.

Spearman correlation is useful for detecting **ordinal or non-linear but monotonic** trends a common scenario in credit scoring when input features are not normally distributed or linearly related to the outcome.
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
from scipy import stats
from scipy.stats import rankdata

import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

"""## Load Dataset

The analysis uses the univariate WOE/IV-prepared dataset, excluding Information Value, to maintain consistency with previous statistical variable assessments.
"""

data = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/Internal_test_0_datasetForUnivariateVSExceptIV.csv', index_col=[0])

data.head()

data.shape

lstfeature = list(data.columns)

len(lstfeature)

"""## Prepare Features

We remove the target variable loan_status from the feature list before computing Spearman correlations.
"""

lstfeature.remove('loan_status')

len(lstfeature)

variable = []
spearman = []
pvalue = []

"""## Compute Spearman Correlation

For each feature, we calculate the Spearman correlation coefficient and its p-value with respect to the target. This helps identify monotonic relationships useful in both logistic regression and tree-based models.
"""

for i in lstfeature:
    variable.append(i)
    spearman.append(stats.spearmanr(data[i], data['loan_status']).statistic)
    pvalue.append(stats.spearmanr(data[i], data['loan_status']).pvalue)

dict = {'variable': variable, 'spearman': spearman, 'pvalue': pvalue}
df = pd.DataFrame(dict)

df

df['spearman'] = df['spearman'].abs()

"""## Rank and Export

We sort features by absolute Spearman coefficient strength and export the ranked list to CSV for use in feature selection and comparison with Hoeffding's D or XGBoost-based importance scores.
"""

df = df.sort_values(by = ['spearman'], ascending = False).reset_index().drop(columns = ['index'])

"""## Interpretation of Spearman Correlation Results

This table ranks features based on their **monotonic correlation** with the target variable loan_status using Spearman’s rank method.

- **previous_loan_defaults_on_file** shows the strongest monotonic relationship (ρ ≈ 0.54), reinforcing its value as a top risk signal, consistently ranked highly across IV, XGBoost, and Hoeffding's D.

- Features like **loan_percent_income**, **loan_int_rate**, and **person_income** also show moderate positive Spearman correlations, suggesting that as these values increase, the likelihood of default tends to increase monotonically.

- **credit_score** and **person_education** have very weak (ρ ≈ 0.01 or less) and statistically non-significant correlations (p > 0.05), indicating limited monotonic predictive power.

> **Note**: A low Spearman value does not necessarily mean the variable is useless — it could still be valuable in nonlinear or interaction-heavy models like Random Forest or XGBoost.

This analysis strengthens confidence in high-performing features and helps deprioritize those with weak and non-monotonic relationships.

"""

df

df.to_csv('/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/spearman.csv')