# -*- coding: utf-8 -*-
"""LR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NA0j2bZu1ZxIWo8lfXQ8X-lm_UbjCJ4j
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

import matplotlib.pyplot as plt
import datetime

pd.set_option('display.max_columns', None)

data = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/Internal_test_0_datasetForUnivariateVSExceptIV.csv', index_col=[0])

data

lstfeature = list(data.columns)

len(lstfeature)

lstfeature.remove('loan_status')

len(lstfeature)

features = []
pvalues = []
coeff = []

for i in lstfeature:
    features.append(i)
    modeldata = data[['loan_status', i]]
    Xtrain = modeldata[[i]]
    Xtrain = sm.add_constant(Xtrain)
    ytrain = modeldata[['loan_status']]

    try:
        log_reg = sm.Logit(ytrain, Xtrain).fit()
        pvalues.append(log_reg.pvalues[i])
        coeff.append(log_reg.params[i])
    except np.linalg.LinAlgError as err:
        if 'Singular matrix' in str(err):
            pvalues.append(1.0)
            coeff.append(0.0)
            continue
        else:
            raise

dict = {'features': features, 'pvalues': pvalues}
df = pd.DataFrame(dict)

df

df = df.sort_values(by = ['pvalues'], ascending = True).reset_index().drop(columns = ['index'])

df.to_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/Internal_LR.csv')