# -*- coding: utf-8 -*-
"""Credit_Risk_Scorecard_Monitoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12wBjl67-fn3UHVqDSruDug2H7rhXkCOz

# Credit Monitoring System

## Environment Setup

This section initializes the core Python libraries required for the credit risk modeling pipeline:

+ pandas and numpy: foundational libraries for structured data manipulation and vectorized numerical operations.

+ seaborn and matplotlib.pyplot: used for exploratory data analysis and diagnostic visualizations, including distribution plots and bivariate summaries.

+ train_test_split (sklearn.model_selection): partitions data into development and validation samples, facilitating robust model performance assessment.

+ LogisticRegression (sklearn.linear_model): serves as a baseline classifier for binary outcomes (e.g., default vs. non-default), commonly used in PD (Probability of Default) modeling under Basel and IFRS 9 frameworks.

+ SimpleImputer (sklearn.impute): handles missing data through rule-based imputation (e.g., mean/mode), supporting regulatory expectations for data completeness.

+ MinMaxScaler (sklearn.preprocessing): applies feature scaling to normalize variables to a [0, 1] range — particularly useful in downstream scorecard scaling and model convergence.
"""

import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler

import matplotlib.pyplot as plt

"""## Data Setup

In production-grade credit risk modeling, it is standard practice to validate model performance across temporal splits, comparing results on development (historical) data against more recent, out-of-time samples. This allows for assessment of model stability, robustness, and the detection of both data drift (changes in input distributions) and concept drift (changes in the relationship between predictors and the outcome).

In the absence of time-stamped observations, we simulate this structure using pre-partitioned datasets:

+ train: used as a proxy for development data, reflecting older customer records with known outcomes.

+ test: used as a proxy for recent data, representing newer accounts and simulating future applicants under production conditions.

This proxy framework enables:

+ Out-of-time performance benchmarking

+ Stability index analysis (e.g., PSI)

+ Realistic validation under production-like temporal drift scenarios
"""

dev_data = pd.read_csv(r'/content/cs-training.csv')

rec_data = pd.read_csv(r'/content/cs-test.csv')

"""## Building a Simulated Internal Credit Scorecard

In the absence of an established internal scorecard, this section constructs a simplified credit risk model using logistic regression. While production-grade scorecards typically incorporate expert-derived rules, segmentation logic, overrides, and comply with regulatory frameworks (e.g., Basel II/III, IFRS 9), our objective here is to develop a baseline statistical model to support score monitoring and stability analysis.

The model outputs an internal scoring variable (Internal_Credit_Scoring) and corresponding probability of default (PD) estimates. These will be used in subsequent sections to assess:

+ Population drift via distributional changes over time (e.g., PSI)

+ Score stability across development vs. recent samples

+ Portfolio degradation and shifts in risk segmentation over time

### Step 1: Simulated Internal Scorecard Using Logistic Regression

Key Assumptions and Governance Considerations:

+ Age is excluded due to its sensitivity under fair lending regulations, such as the U.S. Equal Credit Opportunity Act (ECOA). While age may be included under strict justification and monitoring, we omit it here to avoid potential compliance concerns.

+ The purpose of this model is not optimization or production deployment, but rather to generate a reasonable, interpretable internal score to support post-modeling diagnostics such as population stability monitoring and early signal detection.

+ As part of scorecard transparency and governance, the logit equation is explicitly outputted. This enables auditability, interpretability, and challenger model development practices often mandated in regulated environments before production approval.
"""

df_train = dev_data.copy()
df_train = df_train.drop(columns=['Unnamed: 0', 'age'])

X = df_train.drop(columns='SeriousDlqin2yrs')
y = df_train['SeriousDlqin2yrs']

imputer = SimpleImputer(strategy='median')
scaler = MinMaxScaler()
X_imputed = imputer.fit_transform(X)
X_scaled = scaler.fit_transform(X_imputed)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

logit_train = model.intercept_[0] + np.dot(X_scaled, model.coef_[0])
p_train = 1 / (1 + np.exp(-logit_train))
score_train = 850 - (p_train * 550)

df_train["Default_Probability"] = p_train
df_train["Internal_Credit_Score"] = score_train

coefficients = model.coef_[0]
intercept = model.intercept_[0]
feature_names = X.columns

logit_terms = [f"{coef:.4f} * {name}" for coef, name in zip(coefficients, feature_names)]
logit_expression = f"{intercept:.4f} + " + " + ".join(logit_terms)

print("Compute logit (z)")
print(f"logit = {logit_expression}\n")

print("Compute probability of default")
print("P_default = 1 / (1 + exp(-logit))\n")

print("Compute Internal_Credit_Score Score")
print("Customer_Score = 850 - (P_default * 550)\n")

"""The coefficients above define a logistic regression-based scorecard that estimates the probability of default.

We use this probability to derive an internal credit score on a 300–850 scale:
Internal_Credit_Score = 850 - (P_default * 550)

### Step 2: Use the formula to score the test set

I applied the trained logistic regression model to the recent dataset, using the same imputation and scaling parameters established during model development. This ensures consistency in data preprocessing and mirrors the conditions a production model would expect when scoring new applicants.

For each observation, I calculated the logit score using the model coefficients, converted it to a probability of default (P_default), and then transformed that into an internal credit score on a 300–850 scale. This simulated score allows me to evaluate recent applicants in a way that is consistent with the original scorecard logic.

These outputs are stored in df_test and will be used for downstream monitoring tasks, such as Population Stability Index (PSI) analysis and score distribution tracking, to detect potential drift or degradation in the scoring system.
"""

df_test = rec_data.copy()
df_test = df_test.drop(columns=['Unnamed: 0', 'age'], errors='ignore')
X_test_features = df_test.drop(columns=['SeriousDlqin2yrs'], errors='ignore')

X_test_imputed = imputer.transform(X_test_features)
X_test_scaled = scaler.transform(X_test_imputed)

logit_test = intercept + np.dot(X_test_scaled, coefficients)
p_test = 1 / (1 + np.exp(-logit_test))
score_test = 850 - (p_test * 550)

df_test["Default_Probability"] = p_test
df_test["Internal_Credit_Score"] = score_test

print("\nSample of df_train:")
print(df_train[["Default_Probability", "Internal_Credit_Score"]].head())

print("\nSample of df_test:")
print(df_test[["Default_Probability", "Internal_Credit_Score"]].head())

dev_data[["Default_Probability", "Internal_Credit_Score"]] = df_train[["Default_Probability", "Internal_Credit_Score"]]
rec_data[["Default_Probability", "Internal_Credit_Score"]] = df_test[["Default_Probability", "Internal_Credit_Score"]]

"""## PSI (Population Shift Index)

In this section, I calculate the Population Stability Index (PSI) to assess whether the distribution of the internal credit score has shifted between the development and recent datasets.

PSI is a widely used monitoring metric in credit risk. It helps quantify population drift, which may signal:

+ Model performance degradation

+ Shifts in customer behavior

+ Operational or policy changes

+ Data integrity or pipeline issues

To simulate this, I compare the Internal_Credit_Score from the development dataset (used to train the model) with the recent dataset (representing newer applicants). I divide the scores into decile bins using qcut on the development data, then apply the same bin edges to the recent dataset using cut, ensuring a consistent comparison.

For each score band, I calculate:

+ The proportion of applicants in each dataset

+ The change in distribution (% change)

+ The ratio of proportions (recent vs. development)

+ The natural log of the ratio (Weight of Evidence)

+ The PSI contribution for that bin

Finally, I aggregate the contributions to calculate the total PSI, which quantifies the overall shift in the population. A higher PSI may indicate distributional instability and suggest the need for model recalibration or further investigation.

The PSI report I generated includes the following columns:

+ Score Band: The internal credit score bin, divided into deciles to group applicants by risk level.

+ Development Apps #: Number of applicants in each score band during the development period.

+ Current Apps #: Number of applicants in the same score bands in the recent dataset.

+ Development %: Proportion of the development population in each score band.

+ Current %: Proportion of the recent population in each score band.

+ Change (decimal): Absolute percentage point difference between the two distributions.

+ Ratio (Current % / Development %): Ratio of recent to development proportions. Values above 1 indicate growth in that band; values below 1 indicate decline.

+ WOE ln(Ratio): Natural log of the ratio, used to assess directional impact.

+ Contribution to Index: The PSI contribution from each band. The sum across all rows gives the total PSI value.

### Create decile bins using development data
"""

assert 'Internal_Credit_Score' in dev_data.columns
assert 'Internal_Credit_Score' in rec_data.columns

dev_data['Score_Band'] = pd.qcut(dev_data['Internal_Credit_Score'], q=10, duplicates='drop')

bin_edges = dev_data['Score_Band'].cat.categories
rec_data['Score_Band'] = pd.cut(rec_data['Internal_Credit_Score'], bins=bin_edges, include_lowest=True)

dev_data['Dataset'] = 'Development'
rec_data['Dataset'] = 'Recent'

df = pd.concat([dev_data, rec_data], ignore_index=True)

"""### PSI Calculation Table"""

dev_data = df[df['Dataset'] == 'Development']
recent_data = df[df['Dataset'] == 'Recent']

dev_apps = dev_data['Score_Band'].value_counts().sort_index()
recent_apps = recent_data['Score_Band'].value_counts().sort_index()

dev_percent = dev_apps / dev_apps.sum() * 100
recent_percent = recent_apps / recent_apps.sum() * 100

change_percent = recent_percent - dev_percent
ratio = recent_percent / dev_percent.replace(0, np.nan)
woe = np.log(ratio.replace([np.inf, -np.inf], 0)).replace([np.inf, -np.inf], 0)
psi_contribution = (recent_percent - dev_percent) * woe

psi_report = pd.DataFrame({
    'Score Band': dev_apps.index.astype(str),
    'Development Apps #': dev_apps,
    'Current Apps #': recent_apps,
    'Development %': dev_percent.round(2),
    'Current %': recent_percent.round(2),
    'Change (decimal)': change_percent.round(2),
    'Ratio (Current % / Development %)': ratio.round(2),
    'WOE ln(Ratio)': woe.round(2),
    'Contribution to Index': psi_contribution.round(2)
})

total_row = pd.DataFrame({
    'Score Band': ['Total'],
    'Development Apps #': [dev_apps.sum()],
    'Current Apps #': [recent_apps.sum()],
    'Development %': [dev_percent.sum()],
    'Current %': [recent_percent.sum()],
    'Change (decimal)': [change_percent.sum()],
    'Ratio (Current % / Development %)': [None],
    'WOE ln(Ratio)': [None],
    'Contribution to Index': [psi_contribution.sum()]
})

psi_report = pd.concat([psi_report, total_row], ignore_index=True)
psi_report

"""### Interpretation

**Total PSI Value: 0.027975**

Since the total PSI is approximately 0.028, which is well below the 0.10 threshold, this indicates that:

There is no significant shift in the score distribution between the development and recent populations.

The model appears stable, with no immediate signs of population drift or concept degradation.

No corrective action is required at this stage, though continued monitoring is recommended as part of standard governance.

This interpretation is based on commonly accepted PSI thresholds:

+ PSI < 0.10 → No meaningful change (stable)

+ 0.10 ≤ PSI < 0.25 → Moderate shift (monitor closely)

+ PSI ≥ 0.25 → Significant shift (potentially problematic)

# CSI

In this section, I calculate the Characteristic Stability Index (CSI) to evaluate the stability of individual model features over time. While the Population Stability Index (PSI) focuses on shifts in the overall score distribution, CSI analyzes feature-level distribution changes between the development and recent datasets.

CSI is particularly useful in identifying which variables may be contributing to population drift or model degradation. A high CSI for a specific feature can indicate:

+ A shift in how the feature is distributed in the applicant population

+ A potential need for feature monitoring, rebinning, or retraining

+ Operational, economic, or policy changes affecting that variable

For each feature in the model, I:

+ Segment values into deciles based on the development dataset

+ Compare bin distributions between development and recent samples

+ Compute Weight of Evidence (WoE), distribution shifts, and CSI contributions

+ Assign a score to each bin to visualize directional change

This approach provides detailed visibility into how each feature behaves over time and complements the broader population-level insights provided by PSI.

### Creating the Function
"""

def compute_csi(df, feature, bin_config, min_score=10, max_score=50):
    df = df.copy()
    bin_col = f"{feature}_Bins"

    df[bin_col] = pd.qcut(df[feature], q=10, duplicates='drop')

    dev_data = df[df['Dataset'] == 'Development']
    rec_data = df[df['Dataset'] == 'Recent']

    dev_counts = dev_data[bin_col].value_counts().sort_index()
    rec_counts = rec_data[bin_col].value_counts().sort_index()

    all_bins = dev_counts.index.union(rec_counts.index)
    dev_counts = dev_counts.reindex(all_bins, fill_value=0)
    rec_counts = rec_counts.reindex(all_bins, fill_value=0)

    dev_percent = (dev_counts / dev_counts.sum()) * 100
    rec_percent = (rec_counts / rec_counts.sum()) * 100
    change_percent = rec_percent - dev_percent

    ratio = rec_percent / dev_percent.replace(0, np.nan)
    ratio.replace([np.inf, -np.inf], 0, inplace=True)
    woe = np.log(ratio.replace(0, np.nan)).replace([np.inf, -np.inf], 0).fillna(0)

    psi_contrib = (rec_percent - dev_percent) * woe

    if woe.max() == woe.min():
        score_for_attribute = pd.Series(min_score, index=woe.index)
    else:
        score_for_attribute = min_score + (woe - woe.min()) * (max_score - min_score) / (woe.max() - woe.min())

    score_diff = change_percent * score_for_attribute

    csi_report = pd.DataFrame({
        f'{feature} Bins': all_bins.astype(str),
        'Development Apps #': dev_counts,
        'Current Apps #': rec_counts,
        'Development %': dev_percent.round(2),
        'Current %': rec_percent.round(2),
        'Change (decimal)': change_percent.round(2),
        'Ratio (Current % / Development %)': ratio.round(2),
        'WOE ln(Ratio)': woe.round(2),
        'Contribution to Index': psi_contrib.round(2),
        'Score for Attribute': score_for_attribute.round(2),
        'Score Difference': score_diff.round(2)
    })

    total_row = pd.DataFrame({
        f'{feature} Bins': ['Total'],
        'Development Apps #': [dev_counts.sum()],
        'Current Apps #': [rec_counts.sum()],
        'Development %': [dev_percent.sum()],
        'Current %': [rec_percent.sum()],
        'Change (decimal)': [change_percent.sum()],
        'Ratio (Current % / Development %)': [None],
        'WOE ln(Ratio)': [None],
        'Contribution to Index': [psi_contrib.sum()],
        'Score for Attribute': [None],
        'Score Difference': [score_diff.sum()]
    })

    return pd.concat([csi_report, total_row], ignore_index=True)

"""### Running the Function"""

bin_config = {}
dev_data['Dataset'] = 'Development'
rec_data['Dataset'] = 'Recent'
df_all = pd.concat([dev_data, rec_data], ignore_index=True)

exclude_cols = ['SeriousDlqin2yrs', 'Default_Probability', 'Internal_Credit_Score', 'Dataset']
model_features = [col for col in dev_data.columns if col not in exclude_cols]

full_csi_reports = {}

for feature in model_features:
    print(f"\n Full CSI Table for Feature: {feature}")
    try:
        csi_df = compute_csi(df_all, feature, bin_config)
        full_csi_reports[feature] = csi_df

        display(csi_df)

        csi_plot_df = csi_df[csi_df[f'{feature} Bins'] != 'Total']
        x = np.arange(len(csi_plot_df))
        width = 0.35

        fig, ax = plt.subplots(figsize=(14, 6))
        ax.bar(x - width/2, csi_plot_df['Development %'], width, label='Development')
        ax.bar(x + width/2, csi_plot_df['Current %'], width, label='Recent')

        ax.set_xlabel(f"{feature} Bins")
        ax.set_ylabel("Percentage (%)")
        ax.set_title(f"Development vs Recent Distribution for {feature}")
        ax.set_xticks(x)
        ax.set_xticklabels(csi_plot_df[f'{feature} Bins'], rotation=45, ha='right')
        ax.legend()
        plt.tight_layout()
        plt.show()

    except Exception as e:
        print(f"[ERROR] Failed to compute CSI for {feature}: {e}")

"""### Interpreting CSI Score Difference

I calculated the Characteristic Stability Index (CSI) for each model feature to assess how its distribution has changed between the development and recent datasets. A low CSI indicates that the feature remains stable over time, while higher values may suggest drift or operational change.

Below is the summary of results:
"""

print("\nFinal Stability Summary by Feature:\n")

for feature, csi_df in full_csi_reports.items():
    try:
        total_score_diff = csi_df.loc[csi_df[f'{feature} Bins'] == 'Total', 'Score Difference'].values[0]
        total_csi = csi_df.loc[csi_df[f'{feature} Bins'] == 'Total', 'Contribution to Index'].values[0]
        print(f"* {feature}: CSI = {total_csi:.4f}, Score Difference = {total_score_diff:.2f}")
    except Exception as e:
        print(f"Could not extract metrics for {feature}: {e}")

"""### Recommendations

Most features show low CSI values (below 0.05), which indicates strong stability. MonthlyIncome shows a slightly higher CSI at 0.0403, suggesting a modest shift in income distribution that may be worth monitoring.

These results help identify which features remain reliable and which may need closer attention in ongoing monitoring or model updates.

### Action Points

Based on the results of the PSI and CSI analyses, I identified several actions that would be taken if this were part of a production credit risk model monitoring framework:

+ Flag shifted features and escalate them to model risk or validation teams for further investigation, particularly if they are high-importance drivers.

+ Log findings in a formal monitoring report to track whether trends persist or self-correct over time.

+ Consider refitting or recalibrating the model if the drifted features are found to materially impact predictive performance or if concept drift is suspected.

+ Integrate CSI tracking into an automated monitoring dashboard on a monthly or quarterly basis to enable early detection of future drift and ensure compliance with governance standards.

### KDE Plot of Internal Credit Score Distribution

This KDE plot visualizes the distribution of the Internal_Credit_Score for both the development and recent datasets. While the Population Stability Index (PSI) provides a quantitative measure of distributional shift, this plot offers a visual complement that can help detect subtle changes more intuitively.

+ Blue curve (df_dev) represents the development dataset.

+ Orange curve (df_rec) represents the recent dataset.

The goal is to visually assess whether the score distribution has shifted over time. In a production environment, this type of plot can serve as a regular diagnostic to support stability analysis and drift detection.
"""

import seaborn as sns

df_rec_graph = rec_data.copy()
df_rec_graph['Internal_Credit_Score'] = df_rec_graph['Internal_Credit_Score']

df_dev_graph = dev_data.copy()
df_dev_graph['Internal_Credit_Score'] = df_dev_graph['Internal_Credit_Score']
plt.figure(figsize=(10, 6))
sns.kdeplot(df_dev_graph['Internal_Credit_Score'], fill=True, label='df_dev', alpha=0.5)
sns.kdeplot(df_rec_graph['Internal_Credit_Score'], fill=True, label='df_rec', alpha=0.5)
plt.title('KDE Plot of Score Distributions: Development vs Recent')
plt.xlabel('Internal_Credit_Score')
plt.ylabel('Density')
plt.legend()
plt.grid(True)
plt.show()

"""#### Interpretation

The shapes of the development and recent score distributions are nearly identical, with similar peaks, spread, and central tendency.

This visual alignment is consistent with the earlier low PSI value (~0.028), indicating no significant drift in the score distribution.

There are no signs of secondary peaks, skew, or fat tails in the recent data that would suggest a structural change in applicant behavior or creditworthiness.

#### Conclusion

The KDE plot reinforces the conclusion that the scorecard remains stable across time periods. When combined with the PSI and CSI analyses, this offers strong evidence that the model is operating within its expected performance envelope.

This level of stability is a key indicator of model health and is essential for maintaining trust in production credit risk models. It also provides a solid foundation for ongoing monitoring and governance compliance.

### KDE Plot of Monthly Income Distribution

This KDE plot compares the distribution of the MonthlyIncome feature across the development and recent datasets.

It supports the feature-level drift analysis conducted earlier using CSI, where MonthlyIncome showed a modest shift with a CSI value of 0.0403.

+ Blue curve (df_dev): Applicants in the development dataset

+ Orange curve (df_rec): Applicants in the recent dataset

The objective is to visually inspect whether income levels have shifted over time, which could reflect changes in applicant profiles, economic conditions, or underwriting policies.
"""

import seaborn as sns

df_rec_graph = rec_data.copy()
df_rec_graph['MonthlyIncome'] = df_rec_graph['MonthlyIncome']

df_dev_graph = dev_data.copy()
df_dev_graph['MonthlyIncome'] = df_dev_graph['MonthlyIncome']
plt.figure(figsize=(10, 6))
sns.kdeplot(df_dev_graph['MonthlyIncome'], fill=True, label='df_dev', alpha=0.5)
sns.kdeplot(df_rec_graph['MonthlyIncome'], fill=True, label='df_rec', alpha=0.5)
plt.title('KDE Plot of Score Distributions: Development vs Recent')
plt.xlabel('MonthlyIncome')
plt.ylabel('Density')
plt.legend()
plt.grid(True)
plt.show()

"""### Interpretation

The KDE curves reveal a notable shift in the MonthlyIncome distribution between the development and recent populations.

The recent dataset shows greater concentration in the lower income ranges, along with a thinner right tail, suggesting a decline in higher-income applicants.

This visual shift is consistent with the earlier CSI result for MonthlyIncome, where the Score Difference exceeded 20, indicating a material change in the feature’s distribution.

### Implication

A shift in MonthlyIncome may have a direct impact on the model’s predictive behavior, especially if this feature carries significant weight.

The observed change could be due to:

+ Alterations in how income is reported or imputed

+ A shift in applicant demographics or underwriting strategy

+ Broader macroeconomic conditions affecting applicant pools

### Recommendation

Flag MonthlyIncome for further analysis within the model input validation process.

Incorporate ongoing monitoring of income distributions into the monthly feature stability dashboard.

If this variable contributes significantly to risk prediction, consider performing a performance impact assessment or, if necessary, initiating model recalibration or redevelopment.
"""