# -*- coding: utf-8 -*-
"""VC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7rtXAc5NgnciLZ-EXhxmBWPM_gYaam7

# Variable Clustering (VC) Analysis

In this section, I use **variable clustering** to detect groups of collinear or highly correlated variables. This technique helps reduce multicollinearity and select a more compact set of representative features, especially useful for scorecard models and interpretable ML.

The VarClusHi implementation uses **principal component analysis (PCA)** within clusters to retain meaningful structure while reducing redundancy.
"""

!pip install factor_analyzer

import pandas as pd
import numpy as np
import statsmodels.api as sm

from varclus import VarClusHi

import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

"""## Load Prepared Dataset

This dataset has already been pre-processed through WOE binning and univariate selection. It excludes the Information Value and loan_status columns for the purpose of correlation analysis.
"""

data = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/Internal_test_0_datasetForUnivariateVSExceptIV.csv', index_col=[0])

data.head()

data.shape

"""## Drop Target Variable

loan_status is removed as it's the prediction target and should not influence clustering of input features.
"""

data = data.drop(columns = ['loan_status'])

data.shape

datades = dict(data.describe())
[k for (k,v) in datades.items() if v['std'] == 0]

"""## Run Variable Clustering

We run VarClusHi with:
- maxeigval2=0.7: maximum second eigenvalue threshold to stop splitting a cluster
- maxclus=None: allow the method to determine the optimal number of clusters

This approach identifies feature clusters based on similarity in variance structure.
"""

data_vc = VarClusHi(data,maxeigval2=0.7,maxclus=None)
data_vc.varclus()

data_vc.info

test = data_vc.rsquare

"""## Interpretation of Variable Clustering Results

The table above shows the output of the Variable Clustering procedure:

- **Cluster**: Group of features with similar variance/correlation structure
- **RS_Own**: R² between a feature and its own cluster's first principal component (higher = better fit)
- **RS_NC**: R² between the feature and the nearest *other* cluster center (lower = better separation)
- **RS_Ratio**: Ratio of RS_NC to RS_Own — lower values indicate strong cluster membership

### Key Insights:
- Clusters 0 and 1 group features that are highly correlated:  
  - Cluster 0 includes person_emp_exp and cb_person_cred_hist_length, which are likely proxies for credit history length.  
  - Cluster 1 includes loan_amnt and loan_percent_income, both reflecting loan burden.

- All other features fall into **singleton clusters**, meaning they are not strongly collinear with others — a good sign for model stability.

- Features with **RS_Ratio close to 0** (e.g., credit_score, person_income) are **ideal for retention**, as they are both self-explanatory and statistically distinct.

> These insights will help drive dimensionality reduction by selecting **only one feature per cluster**, often the one with the **highest RS_Own** value or strongest business justification.

"""

test

"""## Export Cluster Results

The output includes each feature’s:
- Assigned cluster
- R-squared with its own cluster center (within-cluster similarity)
- R-squared with the nearest other cluster (cross-cluster similarity)

This helps decide which variable to retain from each group (typically the one with highest within-cluster R²).
"""

test.to_csv('Internal_VC_Results.csv')

test.to_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/Internal_VC_Results.csv')